### ISSUE TITLE
Capitalize address on order screens 

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/ubercart#393] opened 2022-11-19 14:37 UTC
When I uncheck the 'Capitalize address on order screens' option located at admin/store/settings/store in the 'Display settings' vertical tab - Ubercart does not remember the setting and this option is always on and cannot be turned off.

![Firefox_Screenshot_2022-11-19T14-34-59 315Z](https://user-images.githubusercontent.com/14857883/202856229-db718d04-f693-4a71-bad8-2f7aa529250a.png)

**Comment by bugfolder** [comment] 2022-11-19 15:50
This is a duplicate of https://github.com/backdrop-contrib/ubercart/issues/378, which is fixed in the current development version. @amilenkov, can you download the development version and confirm that it's fixed for you?

We'll do a new bugfix release soon that will incorporate this.

**Comment by amilenkov** [comment] 2022-11-19 16:34
Hi, thanks for the reply. Being a non-developer and using GitHub without professional knowledge, I wasn't too sure where to download the "development version" for Ubercart, but I think I managed to do it from here:

https://github.com/backdrop-contrib/ubercart/branches

by downloading version ubercart-1.x-3.x.

I disabled the module, deleted the old Ubercart files from the web server and uploaded ubercart-1.x-3.x. Then I reactivated.

The problem seems to be solved, I am attaching a screenshot.

![Firefox_Screenshot_2022-11-19T16-26-48 402Z](https://user-images.githubusercontent.com/14857883/202861541-a96ce4c8-6f9d-46c8-b825-450ea6360337.png)

**Comment by amilenkov** [comment] 2022-11-19 16:43
I then tried to check which version of Ubercart I'm using, but strangely, Ubercart is missing from the list of modules on the page
admin/reports/updates/list

This is probably normal for "development version", I have not used development versions for modules in Backdrop before and this is the first time I notice this.

**Comment by bugfolder** [comment] 2022-11-19 17:23
Yes, "development versions" don't have the version number applied; that only happens with an official release (the packager applies that information). It's OK, your site will be fine. We'll issue a new release in a week or two—several bugfixes have accumulated over the last month. 

If you want, you could manually add these lines to the bottom of the `ubercart.info` file:

```
; Added by Backdrop CMS packaging script on 2022-10-30
project = ubercart
version = 1.x-3.13.7
timestamp = 1667157299
```

Then it will show up in the list of available updates, and when 1.x-3.13.8 gets released, it will show up as an available update for Ubercart.

**Comment by bugfolder** [comment] 2022-11-21 23:04
[Version 3.13.8 has just been released.](https://backdropcms.org/project/ubercart). @amilenkov, would you please download and install it; it should have fixed this issue (and several others!), and the version will show up properly now and going forward.

**Comment by bugfolder** [comment] 2022-12-19 16:01
I think the issue has been fixed in the latest release, so closing this.

**Closed as completed by bugfolder** 2022-12-19 16:01 UTC
